### ISSUE TITLE
Publish as CLI crate

### ISSUE THREAD

**Issue by sunsided** [pophilpo/image-resize#10]
It would be interesting to be able to `cargo install imres` straight off crates.io. Crates.io provides the [`command-line-utility`](https://crates.io/categories/command-line-utilities) category for use in `Cargo.toml`.

Something like:

```toml
[package]
name = "imres"
version = "0.1.0"
edition = "2021"
description = "A tool that resizes images that are over 1 MB"
homepage = "https://github.com/pophilpo/image-resize"
repository = "https://github.com/pophilpo/image-resize"
authors = ["..."]
# keywords = ["images", "resizing"]
categories = ["command-line-utilities"]
readme = "README.md"
# license = "..."
```
